FROM gcr.io/kaniko-project/executor:v1.23.2 AS kaniko

FROM python:3.11-bookworm

MAINTAINER Raphael Michel
USER root

# Add kaniko to this image by re-using binaries and steps from official image
#
COPY --from=kaniko /kaniko/executor /kaniko/executor
COPY --from=kaniko /kaniko/docker-credential-gcr /kaniko/docker-credential-gcr
COPY --from=kaniko /kaniko/docker-credential-ecr-login /kaniko/docker-credential-ecr-login
COPY --from=kaniko /kaniko/docker-credential-acr-env /kaniko/docker-credential-acr-env
COPY --from=kaniko /etc/nsswitch.conf /etc/nsswitch.conf
COPY --from=kaniko /kaniko/.docker /kaniko/.docker

ENV PATH $PATH:/usr/local/bin:/kaniko
ENV DOCKER_CONFIG /kaniko/.docker/
ENV DOCKER_CREDENTIAL_GCR_CONFIG /kaniko/.config/gcloud/docker_credential_gcr_config.json

# Regular pretix build environment steps
RUN apt-get update && \
	apt-get install -y git \
	    libxml2-dev libxslt1-dev python3-virtualenv locales libffi-dev \
     	build-essential python3-dev zlib1g-dev libssl-dev gettext git ghostscript \
	    libmemcached-dev libjpeg-dev libpq-dev pdftk bzip2 \
	    wget tar openssh-client libmaxminddb0 libmaxminddb-dev \
	    libluajit-5.1-dev pkg-config libxmlsec1-dev libxmlsec1-openssl nodejs npm \
		aspell-en rsync sudo \
	    --no-install-recommends && \
		apt-get clean && \
		rm -rf /var/lib/apt/lists/* && \
		dpkg-reconfigure locales && \
		locale-gen C.UTF-8 && \
		/usr/sbin/update-locale LANG=C.UTF-8

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

WORKDIR /
RUN pip install virtualenv uv

CMD ["/bin/bash"]
